[package]
name = "cosmic-text-issue-151-repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-text = "0.9.0"
tiny-skia = "0.11.1"
tracing-subscriber = "0.3.17"
